--- #YAML:1.0
name:               Mojolicious-Plugin-MailException
version:            0.16
abstract:           Mojolicious plugin to send crash information by email
author:
    - Dmitry E. Oboukhov <unera@debian.org>
license:            Perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    MIME::Lite:   0
    MIME::Words:  0
    Mojolicious:  0
resources:
    bugtracker:  https://github.com/dr-co/libmojolicious-plugin-mail_exception/issues
    homepage:    https://github.com/dr-co/libmojolicious-plugin-mail_exception
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
