---
abstract: 'Mojolicious plugin to send crash information by email'
author:
  - 'Dmitry E. Oboukhov <unera@debian.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-MailException
no_index:
  directory:
    - t
    - inc
requires:
  MIME::Lite: 0
  MIME::Words: 0
  Mojolicious: 0
resources:
  bugtracker: https://github.com/dr-co/libmojolicious-plugin-mail_exception/issues
  homepage: https://github.com/dr-co/libmojolicious-plugin-mail_exception
  repository: https://github.com/dr-co/libmojolicious-plugin-mail_exception
version: 0.19
